/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package net.flectone.swing.frames;

import com.formdev.flatlaf.ui.FlatButtonBorder;
import net.flectone.Main;
import net.flectone.swing.panels.MainPanel;
import net.flectone.system.Configuration;
import net.flectone.system.SystemInfo;
import net.flectone.utils.Dialog;
import net.flectone.utils.SwingUtils;

import javax.swing.*;
import javax.swing.colorchooser.AbstractColorChooserPanel;
import java.util.HashMap;

/**
 *
 * @author TheFaser
 */
public class SettingsFrame extends EmptyFrame {

    /** Creates new form SettingsFrame */

    public SettingsFrame() {
        initComponents();
        setVisible(true);

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        jTextField1.setText(SystemInfo.getMinecraftPath());

        dialogButton.addActionListener(e -> {
            Dialog.showSelectMinecraftFolder();
            jTextField1.setText(SystemInfo.getMinecraftPath());
        });

        jTextField1.setEditable(false);

        clearColorChooser();

        jColorChooser1.setColor(SwingUtils.getColor(0));

        HashMap<String, String> languageMap = new HashMap<>();

        String[] languages = Configuration.getValues("support.languages");

        for(int x = 0; x < languages.length; x++){

            String languageValue = Configuration.getValue("language." + languages[x]);

            languageMap.put(languages[x], languageValue);
            languageMap.put(languageValue, languages[x]);

            languages[x] = languageValue;
        }

        jComboBox1.setModel(new DefaultComboBoxModel<>(languages));
        jComboBox1.setSelectedItem(Configuration.getValue("language." + SystemInfo.getLanguage()));

        jComboBox1.addActionListener(e -> {
            String language = languageMap.get(jComboBox1.getSelectedItem());
            SystemInfo.setLanguage(language);

            Main.frame.getContentPane().removeAll();
            Main.frame.getContentPane().add(new MainPanel());
            SwingUtilities.updateComponentTreeUI(Main.frame);

            SwingUtils.clearAllTabs();

            this.dispose();
            new SettingsFrame();
        });

    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jComboBox1 = new JComboBox<>();
        jColorChooser1 = new JColorChooser();
        jButton1 = new JButton();
        jTextField1 = new JTextField();
        jPanel2 = new JPanel();
        languageLabel = new JLabel();
        pathLabel = new JLabel();
        dialogButton = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle(Configuration.getValue("frame.settings"));
        setResizable(false);

        jComboBox1.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText(Configuration.getValue("label.set_color"));
        jButton1.addActionListener(e -> jButton1MouseClicked());

        jTextField1.setBorder(new FlatButtonBorder());

        languageLabel.setText(Configuration.getValue("label.language"));

        pathLabel.setText(Configuration.getValue("label.minecraft_path"));

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(languageLabel, GroupLayout.Alignment.TRAILING)
                    .addComponent(pathLabel, GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pathLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(languageLabel)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        dialogButton.setText("...");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jColorChooser1, GroupLayout.PREFERRED_SIZE, 640, GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jButton1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 339, GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(dialogButton))
                    .addComponent(jComboBox1, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                            .addComponent(dialogButton))
                        .addGap(8, 8, 8)
                        .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jColorChooser1, GroupLayout.PREFERRED_SIZE, 314, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked() {//GEN-FIRST:event_jButton1MouseClicked
        SwingUtils.setColors(jColorChooser1.getColor());
        clearColorChooser();
    }//GEN-LAST:event_jButton1MouseClicked

    private void clearColorChooser(){
        AbstractColorChooserPanel[] panels = jColorChooser1.getChooserPanels();
        for (AbstractColorChooserPanel panel : panels) {
            if (!panel.getDisplayName().equals("HSV")) {
                jColorChooser1.removeChooserPanel(panel);
            } else {

                JPanel hsvPanelComponent = ((JPanel) panel.getComponents()[0]);
                hsvPanelComponent.remove(3);
                hsvPanelComponent.remove(7);
                hsvPanelComponent.remove(11);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton dialogButton;
    private JButton jButton1;
    private JColorChooser jColorChooser1;
    private JComboBox<String> jComboBox1;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JTextField jTextField1;
    private JLabel languageLabel;
    private JLabel pathLabel;
    // End of variables declaration//GEN-END:variables

}
