/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package net.flectone.swing.panels.installations;

import net.flectone.swing.panels.test.CustomPanel;
import net.flectone.system.Configuration;
import net.flectone.system.Installation;
import net.flectone.utils.Dialog;
import net.flectone.utils.SwingUtils;

import javax.swing.*;
import java.io.File;

/**
 *
 * @author TheFaser
 */
public class ModsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ModsPanel
     */

    public CustomPanel panel;

    public ModsPanel() {

        panel = new CustomPanel("mods", ".jar");

        initComponents();

        versionComboBox.setModel(new DefaultComboBoxModel<>(Configuration.getValues("support.user_mods.versions")));
        versionComboBox.addActionListener(e -> {
            SwingUtils.clearTabsComponents("mods");
            updateComponents();
        });

        loaderComboBox.setModel(new DefaultComboBoxModel<>(Configuration.getValues("support.loaders_type")));
        loaderComboBox.addActionListener(e -> {
            SwingUtils.clearTabsComponents("mods");
            updateComponents();
        });

        updateComponents();

        panel.addComponentsToInstallPanel(this);

        installButton.addActionListener(e -> new Thread(() -> {

            installButton.setEnabled(false);
            installButton1.setEnabled(false);

            Installation installation = new Installation("mods",
                    ".jar",
                    panel.getUrlToComponents() + "/",
                    "mods" + File.separator,
                    panel.getProgressPanel());


            installation.downloadFiles();
            installation.close();

            installButton.setEnabled(true);
            installButton1.setEnabled(true);
        }).start());

        installButton1.addActionListener(e -> new Thread(() ->{

            installButton.setEnabled(false);
            installButton1.setEnabled(false);

            Installation installation = new Installation("mods",
                    ".jar",
                    panel.getUrlToComponents() + "/",
                    "mods" + File.separator,
                    panel.getProgressPanel());

            installation.updateExistFiles(panel.getComponentsList());
            installation.close();

            installButton.setEnabled(true);
            installButton1.setEnabled(true);
        }).start());

        jButton2.addActionListener(e -> Dialog.showSelectMinecraftFolder());

    }

    private void updateComponents(){

        panel.setUrlToComponents("components/mods/" + versionComboBox.getSelectedItem() + "/" + loaderComboBox.getSelectedItem());
        panel.updateComponents((builder, component) -> {
            builder.addIcon("components/" + component + ".png")
                    .addCheckBox(Configuration.getValue("checkbox.install") + Configuration.getValue("mod." + component), component)
                    .addText("label." + component)
                    .addLine();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        versionComboBox = new javax.swing.JComboBox<>();
        installButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        loaderComboBox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        loaderLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        installButton1 = new javax.swing.JButton();

        setOpaque(false);

        jPanel2.setOpaque(false);

        versionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        installButton.setText(Configuration.getValue("label.install"));

        jButton2.setText("...");

        loaderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel3.setOpaque(false);

        loaderLabel.setText(Configuration.getValue("label.loader_type"));

        versionLabel.setText(Configuration.getValue("label.minecraft_version"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(versionLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(loaderLabel)))
                .addGap(2, 2, 2))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(versionLabel)
                .addGap(10, 10, 10)
                .addComponent(loaderLabel)
                .addGap(0, 0, 0))
        );

        installButton1.setText(Configuration.getValue("label.update"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(versionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(loaderComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(installButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(installButton1)
                        .addGap(0, 0, 0)))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(versionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loaderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(installButton)
                    .addComponent(jButton2)
                    .addComponent(installButton1))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton installButton;
    private javax.swing.JButton installButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> loaderComboBox;
    private javax.swing.JLabel loaderLabel;
    private javax.swing.JComboBox<String> versionComboBox;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
