/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package net.flectone.swing.panels.installations;

import com.formdev.flatlaf.ui.FlatButtonBorder;
import net.flectone.system.Configuration;
import net.flectone.utils.SwingUtils;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author TheFaser
 */
public class SearchPanel extends JPanel {

    /**
     * Creates new form SearchPanel
     */

    private final String tab;

    public SearchPanel(String tab) {

        initComponents();
        this.tab = tab;

        selectButton.addActionListener(e -> {
            boolean isChange = !selectButton.getText().equals(Configuration.getValue("button.select_all.true"));

            selectButton.setText(Configuration.getValue("button.select_all." + isChange));
            SwingUtils.getTabsComponents(tab).stream()
                    .filter(component -> component instanceof JCheckBox)
                    .map(component -> (JCheckBox) component)
                    .forEach(checkbox -> checkbox.setSelected(!isChange));
        });
    }

    public void updateSearchLabel(){

        searchLabel.setText(Configuration.getValue("label.search.start") +
                SwingUtils.getTabsComponents(tab).stream()
                        .filter(component -> component instanceof JPanel)
                        .count());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchField = new JTextField();
        selectButton = new JButton();
        searchLabel = new JLabel();

        setOpaque(false);

        searchField.setText(Configuration.getValue("textfield.search"));
        searchField.setBorder(new FlatButtonBorder());
        searchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFieldFocusLost(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        selectButton.setText(Configuration.getValue("button.select_all.true"));

    searchLabel.setText(Configuration.getValue("label.all_components"));

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(searchLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchField, GroupLayout.PREFERRED_SIZE, 256, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectButton)))
                .addContainerGap(374, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(searchLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(selectButton)
                    .addComponent(searchField))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        String searchText = searchField.getText().toLowerCase();

        int countVisiblePanels = 0;

        for (JComponent component : SwingUtils.getTabsComponents(tab)) {

            if (!(component instanceof JPanel)) continue;

            component.setVisible(false);
            for (Component boxComponent : ((Box) component.getComponent(2)).getComponents()) {

                if(boxComponent.getName() == null) continue;

                if(boxComponent.getName().toLowerCase().contains(searchText)) {
                    component.setVisible(true);
                    countVisiblePanels++;
                    break;
                }
            }

        }

        if (countVisiblePanels == 0) {
            searchLabel.setText(Configuration.getValue("label.search.zero"));
        } else if(searchText.isEmpty()){
            searchLabel.setText(Configuration.getValue("label.search.start") + countVisiblePanels);
        } else {
            searchLabel.setText(Configuration.getValue("label.search.custom") + countVisiblePanels);
        }

    }//GEN-LAST:event_searchFieldKeyReleased

    private void searchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFieldFocusLost
        if(!searchField.getText().isEmpty()) return;
        searchField.setText(Configuration.getValue("textfield.search"));
        searchField.setForeground(searchField.getForeground().darker());
    }//GEN-LAST:event_searchFieldFocusLost

    private void searchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFieldFocusGained
        if(!searchField.getText().equals(Configuration.getValue("textfield.search"))) return;
        searchField.setText("");
        searchField.setForeground(new JLabel().getForeground());
    }//GEN-LAST:event_searchFieldFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextField searchField;
    private JLabel searchLabel;
    private JButton selectButton;
    // End of variables declaration//GEN-END:variables
}
